version: '3.9'
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=
    restart: always 
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_TYPE=
      - PG_HOST= 
      - PG_USER=
      - PG_PASSWORD=
      - PG_DB=
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
